spring:
  datasource:
    url: jdbc:h2:mem:test #test at in-memory enviroment
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

#TODO : Create dynamic 'Jasypt Decryption key environment variable' in Git Actions CICD
#TODO : Before test, we need this environment for 'JasyptConfig.class'
#TODO : After self test, RollBack the enviroment for safe